name: robot
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - fastapi==0.121.1
      - filelock==3.20.0
      - filetype==1.2.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - glfw==2.10.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.26
      - langchain-community==0.3.24
      - langchain-core==0.3.74
      - langchain-google-genai==2.0.10
      - langchain-huggingface==0.3.0
      - langchain-openai==0.3.29
      - langchain-tavily==0.2.12
      - langchain-text-splitters==0.3.8
      - langchain-upstage==0.7.1
      - langgraph==0.6.6
      - langgraph-checkpoint==2.1.0
      - langgraph-prebuilt==0.6.4
      - langgraph-sdk==0.2.5
      - langsmith==0.3.45
      - marshmallow==3.26.1
      - mujoco==3.3.7
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - numpy==2.2.6
      - openai==1.109.1
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - packaging==25.0
      - pandas==2.3.3
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pypdf==4.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - scipy==1.15.3
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - starlette==0.49.3
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.20.3
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.23.0
prefix: /Volumes/ssd/conda/conda_envs/robot
